project_name: spiffe-connector
before:
  hooks:
    - go mod tidy
builds:
  - id: spiffegen
    binary: spiffegen
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
